const trainSchedule = [
    { scheduledTime: 5, id: '12951', name: 'Mumbai Rajdhani', type: 'EXPRESS', direction: 'East' },
    { scheduledTime: 20, id: '22439', name: 'Vande Bharat', type: 'EXPRESS', direction: 'West' },
    { scheduledTime: 60, id: '54471', name: 'Ghaziabad Local', type: 'LOCAL', direction: 'East' },
    { scheduledTime: 90, id: '64424', name: 'NDLS-GZB EMU', type: 'LOCAL', direction: 'East' },
    { scheduledTime: 120, id: 'GDS-01', name: 'Goods Carrier', type: 'FREIGHT', direction: 'West' },
    { scheduledTime: 150, id: '12011', name: 'Kalka Shatabdi', type: 'EXPRESS', direction: 'East' },
    { scheduledTime: 200, id: '54472', name: 'Delhi Local', type: 'LOCAL', direction: 'West' },
    { scheduledTime: 250, id: '12780', name: 'Goa Express', type: 'EXPRESS', direction: 'West' },
    { scheduledTime: 300, id: 'GDS-02', name: 'Coal Carrier', type: 'FREIGHT', direction: 'East' },
    { scheduledTime: 350, id: '12506', name: 'North East Exp', type: 'EXPRESS', direction: 'East' },
    { scheduledTime: 400, id: '54473', name: 'Meerut Local', type: 'LOCAL', direction: 'East' },
    { scheduledTime: 420, id: 'GDS-03', name: 'Container Rake', type: 'FREIGHT', direction: 'West' },
    { scheduledTime: 450, id: '14205', name: 'Ayodhya Express', type: 'EXPRESS', direction: 'East' },
    { scheduledTime: 500, id: '64401', name: 'GZB-DLI EMU', type: 'LOCAL', direction: 'West' },
    { scheduledTime: 550, id: '20801', name: 'Magadh Express', type: 'EXPRESS', direction: 'West' },
    { scheduledTime: 600, id: 'GDS-04', name: 'Steel Hauler', type: 'FREIGHT', direction: 'East' },
    { scheduledTime: 630, id: '12627', name: 'Karnataka Exp', type: 'EXPRESS', direction: 'East' },
    { scheduledTime: 660, id: '64463', name: 'NDLS-KLK EMU', type: 'LOCAL', direction: 'West' },
    { scheduledTime: 700, id: 'GDS-05', name: 'Cement Rake', type: 'FREIGHT', direction: 'East' },
    { scheduledTime: 730, id: '12419', name: 'Gomti Express', type: 'EXPRESS', direction: 'East' },
    { scheduledTime: 760, id: '54001', name: 'Tilak Bridge Local', type: 'LOCAL', direction: 'West' },
    { scheduledTime: 800, id: '12801', name: 'Purushottam Exp', type: 'EXPRESS', direction: 'East' },
    { scheduledTime: 830, id: '64903', name: 'MTJ-DLI EMU', type: 'LOCAL', direction: 'West' },
    { scheduledTime: 860, id: 'GDS-06', name: 'Fertilizer Rake', type: 'FREIGHT', direction: 'West' }
];